### ISSUE TITLE
Getting Errors when Compiling Source Code in Visual Studio 2019

### ISSUE THREAD

**Issue by ittyabrehman** [pamidur/aspect-injector#133]
**Hi pamidur** ! first of all **thanks** a lot for designing such a great aop solution. I just fork your source code and i am getting errors when hit to build solution. Below screenshot of some errors.
![image](https://user-images.githubusercontent.com/32015354/89637724-15d9b400-d8c4-11ea-82fb-443772feb0da.png)

**Comment by pamidur** [comment]
Hi @ittyabrehman , well I guess it is time for me to write a CONTRIBUTION GUIDE :)

In order to build app you need to initialize FluentIL submodule with 
```bash
git submodule init
```

I'm not sure but you may need additionally change the submodule url in **.gitmodules** from ssh ```git@github.com:pamidur/fluent-il.git``` to https ```https://github.com/pamidur/fluent-il```

I have moved code responsible for low level CIL manipulation into another lib because I want to reuse it another project, but have not made it a nuget package yet.

**Comment by ittyabrehman** [comment]
@pamidur Issue resolved. Thanks for your guidance
