### ISSUE TITLE
Source Not Available

### ISSUE THREAD

**Issue by parand87** [pamidur/aspect-injector#164]
Hi,

I decorated my method with [LogCall] (as you mentioned in the sample), when I try to step into my method while debugging, I encounter "Source Not Available (Source information is missing from the debug information for this module)" error.

My project is a sample one with just AspectInjector installed (.Net Framework 4.7)

![image](https://user-images.githubusercontent.com/11311337/137629124-a081a454-b283-4d3f-ade8-555b37d8b410.png)

**Comment by pamidur** [comment]
Every release is available on nuget as a package,  so for testing you cat get it from there. https://www.nuget.org/packages/AspectInjector/2.6.1-pre1

If you'd like to build from sources,  you'll need to execute `git submodules init` after pulling sources since FluentIL is attached as submodule.

Please let me know if any of these works for you!

**Comment by dieudo25** [comment]
Hello,

I am also facing the error message "Source not available" while debugging my application. 

Although I can access the rest of the code by pressing 'F11', I am looking for a more convenient way to debug the code. 

Do you have any solution for this ?

Thank you.
