### ISSUE TITLE
Mono compatibility

### ISSUE THREAD

**Issue by AlexanderButs** [pamidur/aspect-injector#46]
Hi.

Trying to use Your library on linux with mono. Created simple aspect and trying to compile project with xbuild. Got next error on build stage:

Aspect Injector has started for TestAspectInjector.exe
Assembly has been loaded
Assembly has been patched
Assembly has been written
: error : Error building target AfterCompile: Exception has been thrown by the target of an invocation.
Done building project "/opt/TestAspectInjector/TestAspectInjector.csproj".-- FAILED

Is it compatible with mono?

**Comment by pamidur** [comment]
Hello,

It hasn't been verified against mono yet. It would help if you specify mono version you use.

Thank you.

**Comment by AlexanderButs** [comment]
mono version 3.12.0 is used.

**Comment by pamidur** [comment]
Ok, I found the issue. MSbuild concatenates path chunk using `\` and not platform specific delimiter. We'll fix it soon.
Thank you for the report.

**Comment by pamidur** [comment]
Ok, delimiter has nothing to do with it. xbuild for some reason returns wrong sdk path. So for unix I set sn tool to be always just 'sn' which works well because proper sn tool is linked as /usr/bin/sn.

Changes will take place on next package release, until then you can replace *AspectInjector.props* and *AspectInjector.targets*
