### ISSUE TITLE
Impossible to debug method body that was wrapped around with aspect

### ISSUE THREAD

**Issue by ocherniavskyi** [pamidur/aspect-injector#82]
All breakpoints disappears after debug starts. 
Sometimes breakpoints marked with exclamation mark  with notice: "code is was changed since last time"

![image](https://user-images.githubusercontent.com/45246546/50638061-05818a80-0f65-11e9-9864-78d1bbbdfaf9.png)

**Comment by pamidur** [comment]
The issue is there due to the fact you use old csproj format and thus old debuginfo. I'll look into it and maybe find a way to support old format. Until then you can switch to new debug format (it shouldn't make any difference to your project):
![default](https://user-images.githubusercontent.com/4095184/50639391-ffda7380-0f69-11e9-85e3-2e74ca5390e1.png)

**Comment by ocherniavskyi** [comment]
Yes it works now, thanks a lot

**Comment by pamidur** [comment]
I'll let you know if I can fix it in generic way. Or I'll add it as a known issue.
However issues like this can appear because there are many things(issues) with old csproj format that even Microsoft will not fix. In general I suggest to look at migrating to new csproj format for your projects.

Thanks for your reports, it helps a lot to make AspectInjector better!

**Comment by pamidur** [comment]
It should work now with FULL debug info in 2.0.2

**Comment by ocherniavskyi** [comment]
Quick check shows that now its working.
