### ISSUE TITLE
Usage with IoC container

### ISSUE THREAD

**Issue by ferreirix** [pamidur/aspect-injector#94]
Since most of the modern ASP.NET CORE applications use an IoC to resolve dependencies, is there a way we could make this (excellent) library DI friendly ?

I saw the [security sample](https://github.com/pamidur/aspect-injector/tree/master/samples/Security) where we rely on a Factory to resolve the `ISecurityService`.

Since the Factory has to be in a static method I tried to obtain the `IServiceProvider ` by storing it statically but it clearly is an [anti-pattern](https://github.com/aspnet/DependencyInjection/issues/294) (and David Fowler hates it).

Any tips are wecolme.
Thank you for the great work!

**Comment by pamidur** [comment]
Hi,
Yes, it is antipattern. However since all AOP magic is done in compile time when no instances exist, this antipattern is the only way we can come up with. 
This is even more true for modern asp.net core where no static HttpContext.

Any ideas appreciated :)

**Comment by kargencW** [comment]
i was using like securityservice example and its working..

` public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory factory)
        {
            AspectFactoryServiceCollection.ServiceProvider = app.ApplicationServices;`
` public void CheckAccess(
            [Argument(Source.Method)] MethodBase method,
            [Argument(Source.Injections)] Attribute[] triggers
            )
        {
            var operationName = $"{method.DeclaringType.FullName}.{method.Name}";
            var requestServices = _serviceProvider.GetService<IHttpContextAccessor>();
            var _scopeManager = requestServices.HttpContext.RequestServices.GetService<IScopeManager>();`

**Comment by pamidur** [comment]
Well, yeah, but there is still that ugly antipattern under the hood, isn't it?

**Comment by kargencW** [comment]
yes :) but when needed and you cant find another way, undure  to ugly antipattern.

**Comment by Feofilakt** [comment]
Hello!

> the Factory has to be in a static method

Why?

**Comment by pamidur** [comment]
Hi @Feofilakt , the reason is that I couldn't find another way around the limitation we have: at compile time we don't know about your container instance, it doesn't exist yet. So there are options:
- we bind container and aspects via some static resource (static method, AppDomain service etc)
- we add parameters to the constructor of target type so your container can inject aspects. However majority containers will refuse to inject unknown types, so you'll need to register all aspects. Another issue is that then you cannot use aspects in static classes/methods because there is no constructor to get aspect instance from.

I appreciate all suggestion and ideas on how to make it better!

**Comment by Feofilakt** [comment]
I found https://codereview.stackexchange.com/questions/20341/inject-dependency-into-postsharp-aspect and https://doc.postsharp.net/consuming-dependencies. So probably its because aspects are instantiated at build time (while I still don't understand how one can instantiate a C# class at build time).

**Comment by pamidur** [comment]
These solutions all work the same way, everywhere you have some static resource to bind build-time and run-time:

static factory:
```c#
public override void RuntimeInitialize(MethodBase method)
    {
        // create instance of Abstract Factory
        var abstractFactory = Activator.CreateInstance(AbstractFactoryType);

        // create an instance of dependency, only instances of IAbstractFactory<ILogger> could be here
        // proven by CompileTimeValidate method
        Logger = ((IAbstractFactory<ILogger>)abstractFactory).CreateInstance();
    }
```
static func:
```c#
public class SomeAspect
{
    public static Func<SomeDependency> CreateSomeDependency { get; set; }

    public void OnExecute()
    {
        //Some behavior
        var dependencyINeed = CreateSomeDependency();
        dependencyINeed.DoSomething();
    }
}
```

the same on Postsharp pages :(

**Comment by pamidur** [comment]
see #166 for details
